# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0002_auto_20170224_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='logo',
            new_name='album_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='filetype',
            field=models.CharField(default='mp3', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=200),
        ),
    ]
